export const REGISTER_USER_DATA = 'REGISTER_USER_DATA';
export const HANDLE_ERROR_REGISTER = 'HANDLE_ERROR_REGISTER';
export const LOGIN_USER_DATA = 'LOGIN_USER_DATA';
export const HANDLE_ERROR_LOGIN = 'HANDLE_ERROR_LOGIN';

export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';
export const SET_USER_DATA = 'SET_USER_DATA';
export const REMOVE_REFRESH_TOKEN = 'REMOVE_REFRESH_TOKEN';
export const REMOVE_USER_DATA = 'REMOVE_USER_DATA';
